project:
  type: website
  title: Poppy Riddle's Dissertation
  output-dir: docs

website:
  title: "Home"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - data.qmd
      - results.qmd
      - recommendations.qmd

format:
  html:
    theme:
      - spacelab
      - brand
    css: styles.css
    toc: true



